// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkionTEdMEkpjW0JZsBY1MCLku2S3gCHU',
    appId: '1:54251147633:web:5cfaf89ccf2f145e2026d0',
    messagingSenderId: '54251147633',
    projectId: 'wedding-rental-595ab',
    authDomain: 'wedding-rental-595ab.firebaseapp.com',
    storageBucket: 'wedding-rental-595ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBRstciOpAcbysqU8dspV48LJUlYl_6E',
    appId: '1:54251147633:android:ad44e1660e231d092026d0',
    messagingSenderId: '54251147633',
    projectId: 'wedding-rental-595ab',
    storageBucket: 'wedding-rental-595ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQLZkgMkITZnC0sm4FiyCZFxuz0Ifz_Pw',
    appId: '1:54251147633:ios:7aababdeba680b922026d0',
    messagingSenderId: '54251147633',
    projectId: 'wedding-rental-595ab',
    storageBucket: 'wedding-rental-595ab.appspot.com',
    iosBundleId: 'com.example.vrWeddingRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQLZkgMkITZnC0sm4FiyCZFxuz0Ifz_Pw',
    appId: '1:54251147633:ios:7aababdeba680b922026d0',
    messagingSenderId: '54251147633',
    projectId: 'wedding-rental-595ab',
    storageBucket: 'wedding-rental-595ab.appspot.com',
    iosBundleId: 'com.example.vrWeddingRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkionTEdMEkpjW0JZsBY1MCLku2S3gCHU',
    appId: '1:54251147633:web:325b04eb3d1c618f2026d0',
    messagingSenderId: '54251147633',
    projectId: 'wedding-rental-595ab',
    authDomain: 'wedding-rental-595ab.firebaseapp.com',
    storageBucket: 'wedding-rental-595ab.appspot.com',
  );

}